[build]
  base = "/filmexplorer"
  command = "yarn build"
  functions = "/filmexplorer/built-lambda"
  publish = "/filmexplorer/public"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
